import streamlit as st
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import ai_helper

st.set_page_config(page_title="AI Diet Planner", page_icon="🥗", layout="wide")
try:
    with open("data/style.css") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
except Exception:
    pass

username = st.session_state.get("username", "")
if not username:
    st.warning("🔒 Please login first."); st.stop()

ai_helper.render_ai_sidebar()

# ── Header ──────────────────────────────────────────────────────────────────
st.markdown(f"""
<div class="hero-card">
    <h1>🥗 AI Diet Planner</h1>
    <h3>Get a fully personalised, science-backed nutrition plan generated by AI</h3>
    <p>Fill in your details below and let the AI craft a plan tailored to your goals ·
    {ai_helper.provider_badge()}</p>
</div>
""", unsafe_allow_html=True)

# ── Form ────────────────────────────────────────────────────────────────────
st.markdown('<div class="section-header"><span class="icon">📝</span> Your Details</div>', unsafe_allow_html=True)

left, right = st.columns([2, 1])

with left:
    with st.form("diet_form"):
        r1c1, r1c2, r1c3 = st.columns(3)
        with r1c1:
            age    = st.number_input("🎂 Age", 10, 100, 25)
        with r1c2:
            weight = st.number_input("⚖️ Weight (kg)", 30.0, 200.0, 70.0)
        with r1c3:
            height = st.number_input("📏 Height (cm)", 100.0, 250.0, 170.0)

        r2c1, r2c2, r2c3 = st.columns(3)
        with r2c1:
            gender = st.selectbox("⚧️ Gender", ["Male","Female"])
        with r2c2:
            goal = st.selectbox("🎯 Goal", ["Weight Loss","Muscle Gain","Maintain","Athletic Performance"])
        with r2c3:
            activity = st.selectbox("🏃 Activity Level", [
                "Sedentary","Lightly Active","Moderately Active","Very Active","Extra Active"
            ])

        r3c1, r3c2 = st.columns(2)
        with r3c1:
            diet_type = st.selectbox("🌿 Diet Preference", [
                "No Preference","Vegetarian","Vegan","Keto","High Protein","Mediterranean","Intermittent Fasting"
            ])
        with r3c2:
            allergies = st.text_input("⚠️ Allergies / Intolerances",
                                      placeholder="e.g. lactose, gluten, nuts")

        meals_per_day = st.slider("🍽️ Meals per day", 2, 6, 3)
        extra_notes   = st.text_area("📝 Anything else? (optional)",
                                     placeholder="e.g. I train at 6am, I prefer Indian food, I'm on a budget",
                                     height=70)
        submit = st.form_submit_button("🚀 Generate My Diet Plan", type="primary")

with right:
    st.markdown("""
    <div class="info-card" style="padding:24px;">
        <div class="info-label">📋 Your plan will include</div><br>
        <ul style="color:#94a3b8;font-size:0.88rem;line-height:2.2;padding-left:16px;margin:0;">
            <li>Daily calorie target (TDEE)</li>
            <li>Protein / Carb / Fat breakdown</li>
            <li>Meal-by-meal schedule</li>
            <li>Grocery shopping list</li>
            <li>Hydration targets</li>
            <li>Supplement recommendations</li>
            <li>Pre &amp; post-workout nutrition</li>
        </ul>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="info-card" style="padding:24px;margin-top:14px;">
        <div class="info-label">⚡ Calorie Targets Guide</div><br>
        <table style="width:100%;color:#94a3b8;font-size:0.83rem;border-collapse:collapse;">
            <tr style="border-bottom:1px solid rgba(255,255,255,0.05);">
                <td style="padding:7px 0;">Weight Loss</td>
                <td style="padding:7px 0;text-align:right;color:#a5b4fc;font-weight:700;">Deficit 300–500 kcal</td>
            </tr>
            <tr style="border-bottom:1px solid rgba(255,255,255,0.05);">
                <td style="padding:7px 0;">Muscle Gain</td>
                <td style="padding:7px 0;text-align:right;color:#a5b4fc;font-weight:700;">Surplus 200–400 kcal</td>
            </tr>
            <tr>
                <td style="padding:7px 0;">Maintain</td>
                <td style="padding:7px 0;text-align:right;color:#a5b4fc;font-weight:700;">At TDEE</td>
            </tr>
        </table>
    </div>
    """, unsafe_allow_html=True)

if submit:
    with st.spinner("🥗 AI is crafting your personalised diet plan…"):
        try:
            # Compute BMR for context
            bmr = round(10*weight + 6.25*height - 5*age + (5 if gender=="Male" else -161))
            mult_map = {"Sedentary":1.2,"Lightly Active":1.375,"Moderately Active":1.55,
                        "Very Active":1.725,"Extra Active":1.9}
            tdee = round(bmr * mult_map.get(activity, 1.55))

            prompt = f"""
Create a comprehensive, personalised {meals_per_day}-meal-per-day diet plan for the following person:

**Profile:**
- Age: {age} | Gender: {gender}
- Weight: {weight} kg | Height: {height} cm
- Goal: {goal} | Activity: {activity}
- Diet type: {diet_type}
- Allergies/Intolerances: {allergies if allergies else 'None'}
- BMR: ~{bmr} kcal | TDEE: ~{tdee} kcal
- Extra notes: {extra_notes if extra_notes else 'None'}

**Provide a detailed plan including:**
1. 📊 Daily Calorie & Macro Targets (protein/carbs/fat in grams and %)
2. 🍽️ Full Day Meal Plan (breakfast, lunch, dinner, snacks — with portion sizes)
3. 🛒 Weekly Grocery List (categorised)
4. 💧 Hydration Protocol
5. ⏰ Meal Timing & Pre/Post-Workout Nutrition
6. 💊 Optional Supplement Stack
7. ✅ 5 Practical Tips for sticking to the plan

Use bold headings, tables where helpful, and emojis. Be very specific with food names and gram quantities.
"""
            sys_p = (
                "You are a Registered Dietitian and sports nutritionist with 15 years of experience. "
                "Create detailed, practical, and culturally inclusive diet plans. Always base recommendations "
                "on peer-reviewed nutritional science. Format responses with clear structure and tables."
            )
            result = ai_helper.get_ai_response(prompt, sys_p, max_tokens=2000)

            st.markdown(f'<div style="margin:16px 0 8px;">{ai_helper.provider_badge()}</div>',
                        unsafe_allow_html=True)
            st.markdown("---")
            st.markdown("## 🥗 Your Personalised AI Diet Plan")
            st.write(result)

        except Exception as e:
            st.error(f"❌ AI Error: {e}")